#!/usr/bin/env python3
"""
KidVenture · Fake Data Seeder
Inserts 100 realistic (but fictional) Bay Area kids activity venues into Supabase.
No API keys needed — just SUPABASE_URL and SUPABASE_KEY in .env

Usage:
    python scripts/seed_fake_data.py              # Insert into Supabase
    python scripts/seed_fake_data.py --dry-run    # Print list, skip DB
"""
import sys
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

from app.core.config import settings

# ---------------------------------------------------------------------------
# 100 fake Bay Area kids venues
# Fields: name, city, neighborhood, region, address, lat, lng,
#         category, venue_type, min_age_months, max_age_months,
#         hours, admission, phone, website, rating, review_count,
#         stroller_friendly, has_restrooms
# ---------------------------------------------------------------------------

def h(weekday="9am–5pm", weekend="10am–6pm"):
    return {"monday": weekday, "tuesday": weekday, "wednesday": weekday,
            "thursday": weekday, "friday": weekday,
            "saturday": weekend, "sunday": weekend}

def free():
    return {"child": 0, "adult": 0}

def paid(child, adult=None):
    return {"child": child, "adult": adult or child + 5}

VENUES = [
    # ── SAN FRANCISCO (20) ──────────────────────────────────────────────────
    {
        "name": "Golden Gate Park Children's Playground",
        "city": "San Francisco", "neighborhood": "Golden Gate Park",
        "region": "sf", "address": "320 Bowling Green Dr, San Francisco, CA 94117",
        "lat": 37.7694, "lng": -122.4862,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 120,
        "hours": h("8am–6pm", "8am–7pm"), "admission": free(),
        "phone": "(415) 831-2700", "website": "https://sfrecpark.org",
        "rating": 4.7, "review_count": 2341,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Exploratorium",
        "city": "San Francisco", "neighborhood": "Embarcadero",
        "region": "sf", "address": "Pier 15, San Francisco, CA 94111",
        "lat": 37.7965, "lng": -122.3978,
        "category": "science_center", "venue_type": "indoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–6pm"), "admission": paid(20, 30),
        "phone": "(415) 528-4444", "website": "https://exploratorium.edu",
        "rating": 4.8, "review_count": 8520,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Children's Creativity Museum",
        "city": "San Francisco", "neighborhood": "SOMA",
        "region": "sf", "address": "221 4th St, San Francisco, CA 94103",
        "lat": 37.7821, "lng": -122.4031,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 24, "max_age_months": 120,
        "hours": h("10am–4pm", "10am–5pm"), "admission": paid(14, 14),
        "phone": "(415) 820-3320", "website": "https://creativity.org",
        "rating": 4.5, "review_count": 1870,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "SF Zoo & Gardens",
        "city": "San Francisco", "neighborhood": "Sunset",
        "region": "sf", "address": "Sloat Blvd & Skyline Blvd, San Francisco, CA 94132",
        "lat": 37.7329, "lng": -122.5032,
        "category": "museum", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(15, 25),
        "phone": "(415) 753-7080", "website": "https://sfzoo.org",
        "rating": 4.4, "review_count": 5210,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Randall Museum",
        "city": "San Francisco", "neighborhood": "Corona Heights",
        "region": "sf", "address": "199 Museum Way, San Francisco, CA 94114",
        "lat": 37.7646, "lng": -122.4404,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": free(),
        "phone": "(415) 554-9600", "website": "https://randallmuseum.org",
        "rating": 4.6, "review_count": 923,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Balboa Park Pool",
        "city": "San Francisco", "neighborhood": "Balboa Park",
        "region": "sf", "address": "45 Havelock St, San Francisco, CA 94112",
        "lat": 37.7261, "lng": -122.4421,
        "category": "swimming", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("6am–9pm", "8am–5pm"), "admission": paid(6, 6),
        "phone": "(415) 337-4701", "website": "https://sfrecpark.org",
        "rating": 4.2, "review_count": 340,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Presidio Tunnel Tops",
        "city": "San Francisco", "neighborhood": "Presidio",
        "region": "sf", "address": "210 Lincoln Blvd, San Francisco, CA 94129",
        "lat": 37.7999, "lng": -122.4672,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("5am–10pm", "5am–10pm"), "admission": free(),
        "phone": None, "website": "https://presidio.gov",
        "rating": 4.9, "review_count": 3102,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "SF Public Library — Main Branch Kids Room",
        "city": "San Francisco", "neighborhood": "Civic Center",
        "region": "sf", "address": "100 Larkin St, San Francisco, CA 94102",
        "lat": 37.7789, "lng": -122.4155,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("9am–6pm", "10am–6pm"), "admission": free(),
        "phone": "(415) 557-4400", "website": "https://sfpl.org",
        "rating": 4.5, "review_count": 1450,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Yerba Buena Gardens Carousel",
        "city": "San Francisco", "neighborhood": "SOMA",
        "region": "sf", "address": "750 Howard St, San Francisco, CA 94103",
        "lat": 37.7839, "lng": -122.4027,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 120,
        "hours": h("10am–6pm", "10am–6pm"), "admission": paid(3, 3),
        "phone": None, "website": "https://yerbabuenagardens.com",
        "rating": 4.6, "review_count": 2010,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Mission Dolores Park",
        "city": "San Francisco", "neighborhood": "Mission",
        "region": "sf", "address": "Dolores St & 19th St, San Francisco, CA 94114",
        "lat": 37.7596, "lng": -122.4269,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("6am–10pm", "6am–10pm"), "admission": free(),
        "phone": None, "website": "https://sfrecpark.org",
        "rating": 4.7, "review_count": 6800,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Koret Children's Quarter",
        "city": "San Francisco", "neighborhood": "Golden Gate Park",
        "region": "sf", "address": "Golden Gate Park, San Francisco, CA 94117",
        "lat": 37.7705, "lng": -122.4724,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 18, "max_age_months": 108,
        "hours": h("8am–6pm", "8am–7pm"), "admission": free(),
        "phone": None, "website": "https://sfrecpark.org",
        "rating": 4.6, "review_count": 1540,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Potrero Hill Recreation Center",
        "city": "San Francisco", "neighborhood": "Potrero Hill",
        "region": "sf", "address": "801 Arkansas St, San Francisco, CA 94107",
        "lat": 37.7602, "lng": -122.4014,
        "category": "sports", "venue_type": "both",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("9am–9pm", "9am–5pm"), "admission": free(),
        "phone": "(415) 695-5009", "website": "https://sfrecpark.org",
        "rating": 4.3, "review_count": 280,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Moonbeam Kids Indoor Play",
        "city": "San Francisco", "neighborhood": "Noe Valley",
        "region": "sf", "address": "3916 24th St, San Francisco, CA 94114",
        "lat": 37.7517, "lng": -122.4329,
        "category": "indoor_play", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 72,
        "hours": h("9am–6pm", "9am–6pm"), "admission": paid(12, 0),
        "phone": "(415) 555-0112", "website": None,
        "rating": 4.4, "review_count": 410,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Noe Valley Town Square",
        "city": "San Francisco", "neighborhood": "Noe Valley",
        "region": "sf", "address": "3861 24th St, San Francisco, CA 94114",
        "lat": 37.7512, "lng": -122.4321,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("7am–10pm", "7am–10pm"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.5, "review_count": 620,
        "stroller_friendly": True, "has_restrooms": False,
    },
    {
        "name": "Cartoon Art Museum",
        "city": "San Francisco", "neighborhood": "SOMA",
        "region": "sf", "address": "781 Beach St, San Francisco, CA 94109",
        "lat": 37.8072, "lng": -122.4177,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 60, "max_age_months": 144,
        "hours": h("11am–5pm", "11am–5pm"), "admission": paid(10, 15),
        "phone": "(415) 227-8666", "website": "https://cartoonart.org",
        "rating": 4.5, "review_count": 780,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Crissy Field Center",
        "city": "San Francisco", "neighborhood": "Presidio",
        "region": "sf", "address": "603 Mason St, San Francisco, CA 94129",
        "lat": 37.8038, "lng": -122.4618,
        "category": "nature_trail", "venue_type": "both",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("9am–5pm", "9am–5pm"), "admission": free(),
        "phone": "(415) 561-7752", "website": "https://parksconservancy.org",
        "rating": 4.8, "review_count": 2900,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "SF Bounce — Indoor Trampoline Park",
        "city": "San Francisco", "neighborhood": "Bayview",
        "region": "sf", "address": "1000 3rd St, San Francisco, CA 94158",
        "lat": 37.7682, "lng": -122.3889,
        "category": "trampoline_park", "venue_type": "indoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–8pm", "9am–9pm"), "admission": paid(18, 0),
        "phone": "(415) 555-0181", "website": None,
        "rating": 4.2, "review_count": 530,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Fort Mason Green",
        "city": "San Francisco", "neighborhood": "Marina",
        "region": "sf", "address": "2 Marina Blvd, San Francisco, CA 94123",
        "lat": 37.8072, "lng": -122.4327,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("6am–10pm", "6am–10pm"), "admission": free(),
        "phone": None, "website": "https://fortmason.org",
        "rating": 4.7, "review_count": 1820,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Sunset Neighborhood Library",
        "city": "San Francisco", "neighborhood": "Outer Sunset",
        "region": "sf", "address": "1305 18th Ave, San Francisco, CA 94122",
        "lat": 37.7619, "lng": -122.4759,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–6pm", "10am–5pm"), "admission": free(),
        "phone": "(415) 355-2808", "website": "https://sfpl.org",
        "rating": 4.4, "review_count": 390,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Lands End Coastal Trail",
        "city": "San Francisco", "neighborhood": "Richmond",
        "region": "sf", "address": "680 Point Lobos Ave, San Francisco, CA 94121",
        "lat": 37.7793, "lng": -122.5085,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": "https://nps.gov/goga",
        "rating": 4.9, "review_count": 4500,
        "stroller_friendly": False, "has_restrooms": True,
    },

    # ── PENINSULA (20) ───────────────────────────────────────────────────────
    {
        "name": "Magical Bridge Playground",
        "city": "Palo Alto", "neighborhood": "Rinconada",
        "region": "peninsula", "address": "851 Embarcadero Rd, Palo Alto, CA 94303",
        "lat": 37.4458, "lng": -122.1065,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": "https://magicalbridge.org",
        "rating": 4.9, "review_count": 1920,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Palo Alto Junior Museum & Zoo",
        "city": "Palo Alto", "neighborhood": "Rinconada",
        "region": "peninsula", "address": "1451 Middlefield Rd, Palo Alto, CA 94301",
        "lat": 37.4441, "lng": -122.1374,
        "category": "museum", "venue_type": "both",
        "min_age_months": 12, "max_age_months": 120,
        "hours": h("10am–5pm", "10am–5pm"), "admission": free(),
        "phone": "(650) 329-2111", "website": "https://paloaltozoo.org",
        "rating": 4.6, "review_count": 1430,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "CuriOdyssey Science Museum",
        "city": "San Mateo", "neighborhood": "Coyote Point",
        "region": "peninsula", "address": "1651 Coyote Point Dr, San Mateo, CA 94401",
        "lat": 37.5707, "lng": -122.3183,
        "category": "science_center", "venue_type": "both",
        "min_age_months": 24, "max_age_months": 108,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(13, 18),
        "phone": "(650) 342-7755", "website": "https://curiodyssey.org",
        "rating": 4.6, "review_count": 2100,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Hiller Aviation Museum",
        "city": "San Carlos", "neighborhood": "Airport Area",
        "region": "peninsula", "address": "601 Skyway Rd, San Carlos, CA 94070",
        "lat": 37.5131, "lng": -122.2468,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 48, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(15, 20),
        "phone": "(650) 654-0200", "website": "https://hiller.org",
        "rating": 4.7, "review_count": 1680,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Coyote Point Recreation Area",
        "city": "San Mateo", "neighborhood": "Coyote Point",
        "region": "peninsula", "address": "1701 Coyote Point Dr, San Mateo, CA 94401",
        "lat": 37.5665, "lng": -122.3218,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": paid(6, 6),
        "phone": "(650) 573-2592", "website": "https://parks.smcgov.org",
        "rating": 4.5, "review_count": 3200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Shoreline Park & Lake",
        "city": "Mountain View", "neighborhood": "Shoreline",
        "region": "peninsula", "address": "3070 N Shoreline Blvd, Mountain View, CA 94043",
        "lat": 37.4327, "lng": -122.0818,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": "(650) 903-6392", "website": "https://mountainview.gov",
        "rating": 4.7, "review_count": 4100,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Sunnyvale Community Center Pool",
        "city": "Sunnyvale", "neighborhood": "Downtown",
        "region": "peninsula", "address": "550 E Remington Dr, Sunnyvale, CA 94087",
        "lat": 37.3724, "lng": -122.0170,
        "category": "swimming", "venue_type": "both",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("6am–9pm", "8am–6pm"), "admission": paid(5, 5),
        "phone": "(408) 730-7350", "website": "https://sunnyvale.ca.gov",
        "rating": 4.2, "review_count": 290,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Bedwell Bayfront Park",
        "city": "Menlo Park", "neighborhood": "Bayfront",
        "region": "peninsula", "address": "1600 Marsh Rd, Menlo Park, CA 94025",
        "lat": 37.4775, "lng": -122.1525,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(650) 858-3470", "website": "https://menlopark.gov",
        "rating": 4.5, "review_count": 870,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Redwood City Lathrop House Splash Pad",
        "city": "Redwood City", "neighborhood": "Downtown",
        "region": "peninsula", "address": "627 Hamilton St, Redwood City, CA 94063",
        "lat": 37.4853, "lng": -122.2336,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 6, "max_age_months": 72,
        "hours": h("10am–6pm", "10am–6pm"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.4, "review_count": 420,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "San Mateo Central Park",
        "city": "San Mateo", "neighborhood": "Central",
        "region": "peninsula", "address": "50 E 5th Ave, San Mateo, CA 94401",
        "lat": 37.5698, "lng": -122.3199,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("6am–10pm", "6am–10pm"), "admission": free(),
        "phone": "(650) 522-7400", "website": "https://cityofsanmateo.org",
        "rating": 4.6, "review_count": 1900,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Mountain View Library — Children's Center",
        "city": "Mountain View", "neighborhood": "Downtown",
        "region": "peninsula", "address": "585 Franklin St, Mountain View, CA 94041",
        "lat": 37.3887, "lng": -122.0801,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–9pm", "10am–6pm"), "admission": free(),
        "phone": "(650) 903-6337", "website": "https://mountainview.gov/library",
        "rating": 4.6, "review_count": 560,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Arastradero Preserve",
        "city": "Palo Alto", "neighborhood": "South Palo Alto",
        "region": "peninsula", "address": "1530 Page Mill Rd, Palo Alto, CA 94304",
        "lat": 37.3887, "lng": -122.1509,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(650) 329-2423", "website": "https://cityofpaloalto.org",
        "rating": 4.7, "review_count": 1280,
        "stroller_friendly": False, "has_restrooms": False,
    },
    {
        "name": "Fair Oaks Park Sunnyvale",
        "city": "Sunnyvale", "neighborhood": "Fair Oaks",
        "region": "peninsula", "address": "Lakeside Dr & Wolfe Rd, Sunnyvale, CA 94086",
        "lat": 37.3785, "lng": -122.0098,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.3, "review_count": 340,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Little Big Gym Mountain View",
        "city": "Mountain View", "neighborhood": "Moffett Park",
        "region": "peninsula", "address": "1580 Space Park Dr, Mountain View, CA 94043",
        "lat": 37.4088, "lng": -122.0535,
        "category": "indoor_play", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 72,
        "hours": h("9am–6pm", "9am–6pm"), "admission": paid(14, 0),
        "phone": "(650) 555-0177", "website": None,
        "rating": 4.5, "review_count": 670,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Burlingame Recreation Center Pool",
        "city": "Burlingame", "neighborhood": "Downtown",
        "region": "peninsula", "address": "850 Burlingame Ave, Burlingame, CA 94010",
        "lat": 37.5838, "lng": -122.3649,
        "category": "swimming", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("6am–9pm", "8am–5pm"), "admission": paid(6, 8),
        "phone": "(650) 558-7300", "website": "https://burlingame.org",
        "rating": 4.3, "review_count": 180,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Palo Alto Baylands Nature Preserve",
        "city": "Palo Alto", "neighborhood": "Baylands",
        "region": "peninsula", "address": "2775 Embarcadero Rd, Palo Alto, CA 94303",
        "lat": 37.4611, "lng": -122.1093,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(650) 329-2423", "website": "https://cityofpaloalto.org",
        "rating": 4.8, "review_count": 2400,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Menlo Park Library",
        "city": "Menlo Park", "neighborhood": "Downtown",
        "region": "peninsula", "address": "800 Alma St, Menlo Park, CA 94025",
        "lat": 37.4533, "lng": -122.1823,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–8pm", "10am–5pm"), "admission": free(),
        "phone": "(650) 330-2501", "website": "https://menlopark.gov",
        "rating": 4.6, "review_count": 310,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Redwood City Stulsaft Park",
        "city": "Redwood City", "neighborhood": "Farm Hills",
        "region": "peninsula", "address": "3700 Farm Hill Blvd, Redwood City, CA 94061",
        "lat": 37.4659, "lng": -122.2504,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.7, "review_count": 890,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Kids Junction Indoor Play",
        "city": "San Mateo", "neighborhood": "Hayward Park",
        "region": "peninsula", "address": "200 S Ellsworth Ave, San Mateo, CA 94401",
        "lat": 37.5614, "lng": -122.3149,
        "category": "indoor_play", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 72,
        "hours": h("9am–5pm", "9am–5pm"), "admission": paid(10, 0),
        "phone": "(650) 555-0150", "website": None,
        "rating": 4.3, "review_count": 490,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Roble Farm & Garden — Sunnyvale",
        "city": "Sunnyvale", "neighborhood": "Lakewood",
        "region": "peninsula", "address": "1116 Hollenbeck Ave, Sunnyvale, CA 94087",
        "lat": 37.3597, "lng": -122.0367,
        "category": "farm", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("9am–5pm", "9am–5pm"), "admission": paid(8, 8),
        "phone": "(408) 555-0142", "website": None,
        "rating": 4.4, "review_count": 310,
        "stroller_friendly": True, "has_restrooms": True,
    },

    # ── SOUTH BAY (20) ───────────────────────────────────────────────────────
    {
        "name": "Children's Discovery Museum of San Jose",
        "city": "San Jose", "neighborhood": "Downtown",
        "region": "south_bay", "address": "180 Woz Way, San Jose, CA 95110",
        "lat": 37.3303, "lng": -121.8938,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 12, "max_age_months": 108,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(14, 14),
        "phone": "(408) 298-5437", "website": "https://cdm.org",
        "rating": 4.7, "review_count": 5200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "The Tech Interactive",
        "city": "San Jose", "neighborhood": "Downtown",
        "region": "south_bay", "address": "201 S Market St, San Jose, CA 95113",
        "lat": 37.3318, "lng": -121.8892,
        "category": "science_center", "venue_type": "indoor",
        "min_age_months": 48, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(22, 27),
        "phone": "(408) 294-8324", "website": "https://thetech.org",
        "rating": 4.6, "review_count": 6800,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Happy Hollow Park & Zoo",
        "city": "San Jose", "neighborhood": "Alum Rock",
        "region": "south_bay", "address": "748 Story Rd, San Jose, CA 95112",
        "lat": 37.3320, "lng": -121.8512,
        "category": "museum", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 96,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(11, 15),
        "phone": "(408) 794-6400", "website": "https://happyhollowpark.org",
        "rating": 4.6, "review_count": 3900,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Emma Prusch Farm Park",
        "city": "San Jose", "neighborhood": "East San Jose",
        "region": "south_bay", "address": "647 S King Rd, San Jose, CA 95116",
        "lat": 37.3376, "lng": -121.8332,
        "category": "farm", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(408) 794-7275", "website": "https://sanjoseca.gov",
        "rating": 4.5, "review_count": 1870,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Alum Rock Park",
        "city": "San Jose", "neighborhood": "Alum Rock",
        "region": "south_bay", "address": "15350 Penitencia Creek Rd, San Jose, CA 95127",
        "lat": 37.3812, "lng": -121.8021,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": paid(6, 6),
        "phone": "(408) 259-5477", "website": "https://sanjoseca.gov",
        "rating": 4.6, "review_count": 2700,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Almaden Lake Park",
        "city": "San Jose", "neighborhood": "Almaden Valley",
        "region": "south_bay", "address": "6099 Winfield Blvd, San Jose, CA 95120",
        "lat": 37.2736, "lng": -121.8756,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(408) 535-3570", "website": "https://sanjoseca.gov",
        "rating": 4.6, "review_count": 2100,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Martial Cottle Park",
        "city": "San Jose", "neighborhood": "South San Jose",
        "region": "south_bay", "address": "5261 Snell Ave, San Jose, CA 95123",
        "lat": 37.2578, "lng": -121.8511,
        "category": "farm", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Dusk", "8am–Dusk"), "admission": free(),
        "phone": "(408) 225-0225", "website": "https://parks.sccgov.org",
        "rating": 4.5, "review_count": 880,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Fremont Central Park",
        "city": "Fremont", "neighborhood": "Central Fremont",
        "region": "south_bay", "address": "40204 Paseo Padre Pkwy, Fremont, CA 94538",
        "lat": 37.5477, "lng": -121.9769,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": "(510) 790-5541", "website": "https://fremont.gov",
        "rating": 4.6, "review_count": 2600,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Lake Elizabeth — Fremont",
        "city": "Fremont", "neighborhood": "Central Fremont",
        "region": "south_bay", "address": "40204 Paseo Padre Pkwy, Fremont, CA 94538",
        "lat": 37.5458, "lng": -121.9733,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("6am–10pm", "6am–10pm"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.7, "review_count": 3400,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "The Jump Zone Trampoline Park",
        "city": "San Jose", "neighborhood": "North San Jose",
        "region": "south_bay", "address": "2221 Old Oakland Rd, San Jose, CA 95131",
        "lat": 37.3885, "lng": -121.9031,
        "category": "trampoline_park", "venue_type": "indoor",
        "min_age_months": 48, "max_age_months": 144,
        "hours": h("10am–8pm", "9am–9pm"), "admission": paid(16, 0),
        "phone": "(408) 555-0130", "website": None,
        "rating": 4.3, "review_count": 640,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Santa Clara Swim Center",
        "city": "Santa Clara", "neighborhood": "Downtown",
        "region": "south_bay", "address": "2625 Patricia Dr, Santa Clara, CA 95051",
        "lat": 37.3527, "lng": -121.9629,
        "category": "swimming", "venue_type": "both",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("5:30am–9pm", "8am–6pm"), "admission": paid(5, 6),
        "phone": "(408) 615-3410", "website": "https://santaclaraca.gov",
        "rating": 4.4, "review_count": 510,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Milpitas Library",
        "city": "Milpitas", "neighborhood": "Downtown",
        "region": "south_bay", "address": "160 N Main St, Milpitas, CA 95035",
        "lat": 37.4331, "lng": -121.8990,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–9pm", "10am–6pm"), "admission": free(),
        "phone": "(408) 262-1171", "website": "https://sccl.org",
        "rating": 4.5, "review_count": 380,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Los Gatos Creek County Park",
        "city": "San Jose", "neighborhood": "West San Jose",
        "region": "south_bay", "address": "1250 Dell Ave, Campbell, CA 95008",
        "lat": 37.2878, "lng": -121.9619,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": free(),
        "phone": "(408) 355-2201", "website": "https://parks.sccgov.org",
        "rating": 4.6, "review_count": 1700,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Tiny Tots Playhouse — San Jose",
        "city": "San Jose", "neighborhood": "Willow Glen",
        "region": "south_bay", "address": "1276 Lincoln Ave, San Jose, CA 95125",
        "lat": 37.3037, "lng": -121.8992,
        "category": "indoor_play", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 60,
        "hours": h("9am–5pm", "9am–5pm"), "admission": paid(11, 0),
        "phone": "(408) 555-0189", "website": None,
        "rating": 4.5, "review_count": 530,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Kelly Park — San Jose",
        "city": "San Jose", "neighborhood": "Alum Rock",
        "region": "south_bay", "address": "1300 Senter Rd, San Jose, CA 95112",
        "lat": 37.3224, "lng": -121.8534,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": free(),
        "phone": "(408) 535-3570", "website": "https://sanjoseca.gov",
        "rating": 4.4, "review_count": 1200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Raging Waters San Jose",
        "city": "San Jose", "neighborhood": "Lake Cunningham",
        "region": "south_bay", "address": "2333 S White Rd, San Jose, CA 95148",
        "lat": 37.3326, "lng": -121.8121,
        "category": "swimming", "venue_type": "outdoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–6pm", "10am–7pm"), "admission": paid(45, 50),
        "phone": "(408) 238-9900", "website": "https://rwsanJose.com",
        "rating": 4.3, "review_count": 4500,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Overfelt Gardens",
        "city": "San Jose", "neighborhood": "East San Jose",
        "region": "south_bay", "address": "2145 Educational Park Dr, San Jose, CA 95133",
        "lat": 37.3638, "lng": -121.8453,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": free(),
        "phone": "(408) 251-3323", "website": "https://sanjoseca.gov",
        "rating": 4.5, "review_count": 780,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Campbell Community Center Sports Complex",
        "city": "Campbell", "neighborhood": "Downtown Campbell",
        "region": "south_bay", "address": "1 W Campbell Ave, Campbell, CA 95008",
        "lat": 37.2874, "lng": -121.9497,
        "category": "sports", "venue_type": "both",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("8am–9pm", "8am–5pm"), "admission": paid(5, 5),
        "phone": "(408) 866-2732", "website": "https://campbellca.gov",
        "rating": 4.3, "review_count": 290,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Vasona Lake County Park",
        "city": "Los Gatos", "neighborhood": "Blossom Hill",
        "region": "south_bay", "address": "333 Blossom Hill Rd, Los Gatos, CA 95032",
        "lat": 37.2573, "lng": -121.9756,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": paid(6, 6),
        "phone": "(408) 356-2729", "website": "https://parks.sccgov.org",
        "rating": 4.7, "review_count": 2800,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Fremont Main Library",
        "city": "Fremont", "neighborhood": "Central Fremont",
        "region": "south_bay", "address": "2400 Stevenson Blvd, Fremont, CA 94538",
        "lat": 37.5323, "lng": -121.9882,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–9pm", "10am–6pm"), "admission": free(),
        "phone": "(510) 745-1400", "website": "https://aclibrary.org",
        "rating": 4.5, "review_count": 620,
        "stroller_friendly": True, "has_restrooms": True,
    },

    # ── EAST BAY (20) ────────────────────────────────────────────────────────
    {
        "name": "Oakland Zoo",
        "city": "Oakland", "neighborhood": "Montclair",
        "region": "east_bay", "address": "9777 Golf Links Rd, Oakland, CA 94605",
        "lat": 37.7547, "lng": -122.1499,
        "category": "museum", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("10am–4pm", "10am–5pm"), "admission": paid(22, 28),
        "phone": "(510) 632-9525", "website": "https://oaklandzoo.org",
        "rating": 4.7, "review_count": 7400,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Children's Fairyland",
        "city": "Oakland", "neighborhood": "Grand Lake",
        "region": "east_bay", "address": "699 Bellevue Ave, Oakland, CA 94610",
        "lat": 37.8047, "lng": -122.2534,
        "category": "indoor_play", "venue_type": "outdoor",
        "min_age_months": 6, "max_age_months": 96,
        "hours": h("10am–4pm", "10am–5pm"), "admission": paid(12, 12),
        "phone": "(510) 452-2259", "website": "https://fairyland.org",
        "rating": 4.8, "review_count": 4200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Lawrence Hall of Science",
        "city": "Berkeley", "neighborhood": "Hills",
        "region": "east_bay", "address": "1 Centennial Dr, Berkeley, CA 94720",
        "lat": 37.8782, "lng": -122.2402,
        "category": "science_center", "venue_type": "both",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(18, 22),
        "phone": "(510) 642-5132", "website": "https://lawrencehallofscience.org",
        "rating": 4.6, "review_count": 3100,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Tilden Regional Park",
        "city": "Berkeley", "neighborhood": "Berkeley Hills",
        "region": "east_bay", "address": "2501 Grizzly Peak Blvd, Orinda, CA 94563",
        "lat": 37.9009, "lng": -122.2378,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("5am–10pm", "5am–10pm"), "admission": free(),
        "phone": "(510) 562-7275", "website": "https://ebparks.org",
        "rating": 4.8, "review_count": 5600,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Chabot Space & Science Center",
        "city": "Oakland", "neighborhood": "Redwood Heights",
        "region": "east_bay", "address": "10000 Skyline Blvd, Oakland, CA 94619",
        "lat": 37.8152, "lng": -122.1735,
        "category": "science_center", "venue_type": "indoor",
        "min_age_months": 60, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–5pm"), "admission": paid(18, 23),
        "phone": "(510) 336-7300", "website": "https://chabotspace.org",
        "rating": 4.6, "review_count": 2800,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Totland Playground Berkeley",
        "city": "Berkeley", "neighborhood": "North Berkeley",
        "region": "east_bay", "address": "Virginia St & McGee Ave, Berkeley, CA 94703",
        "lat": 37.8753, "lng": -122.2763,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 72,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.7, "review_count": 980,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Oakland Museum of California",
        "city": "Oakland", "neighborhood": "Lake Merritt",
        "region": "east_bay", "address": "1000 Oak St, Oakland, CA 94607",
        "lat": 37.7979, "lng": -122.2597,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 48, "max_age_months": 144,
        "hours": h("11am–5pm", "10am–6pm"), "admission": paid(16, 20),
        "phone": "(510) 318-8400", "website": "https://museumca.org",
        "rating": 4.5, "review_count": 3200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Berkeley Adventure Playground",
        "city": "Berkeley", "neighborhood": "Marina",
        "region": "east_bay", "address": "160 University Ave, Berkeley, CA 94710",
        "lat": 37.8636, "lng": -122.3085,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 60, "max_age_months": 144,
        "hours": h("Sat–Sun only 10am–5pm", "10am–5pm"), "admission": free(),
        "phone": "(510) 981-6720", "website": "https://cityofberkeley.info",
        "rating": 4.6, "review_count": 720,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Walnut Creek Civic Park Playground",
        "city": "Walnut Creek", "neighborhood": "Downtown",
        "region": "east_bay", "address": "1375 Civic Dr, Walnut Creek, CA 94596",
        "lat": 37.9090, "lng": -122.0664,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 108,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.5, "review_count": 490,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Joaquin Miller Park",
        "city": "Oakland", "neighborhood": "Joaquin Miller",
        "region": "east_bay", "address": "3594 Sanborn Dr, Oakland, CA 94602",
        "lat": 37.8102, "lng": -122.2001,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("5am–10pm", "5am–10pm"), "admission": free(),
        "phone": "(510) 482-7857", "website": "https://ebparks.org",
        "rating": 4.7, "review_count": 2400,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Roberts Regional Recreation Area",
        "city": "Oakland", "neighborhood": "Redwood Regional Park",
        "region": "east_bay", "address": "10570 Skyline Blvd, Oakland, CA 94619",
        "lat": 37.8058, "lng": -122.1564,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("5am–10pm", "5am–10pm"), "admission": paid(5, 5),
        "phone": "(510) 544-3231", "website": "https://ebparks.org",
        "rating": 4.7, "review_count": 1800,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Berkeley Public Library — Children's Section",
        "city": "Berkeley", "neighborhood": "Downtown",
        "region": "east_bay", "address": "2090 Kittredge St, Berkeley, CA 94704",
        "lat": 37.8693, "lng": -122.2676,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–8pm", "10am–6pm"), "admission": free(),
        "phone": "(510) 981-6100", "website": "https://berkeleypubliclibrary.org",
        "rating": 4.5, "review_count": 640,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Lake Merritt Boating Center",
        "city": "Oakland", "neighborhood": "Lake Merritt",
        "region": "east_bay", "address": "568 Bellevue Ave, Oakland, CA 94610",
        "lat": 37.8041, "lng": -122.2538,
        "category": "sports", "venue_type": "outdoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("10am–5pm", "10am–6pm"), "admission": paid(20, 20),
        "phone": "(510) 238-2196", "website": "https://oaklandca.gov",
        "rating": 4.4, "review_count": 890,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Hayward Japanese Gardens",
        "city": "Hayward", "neighborhood": "Downtown",
        "region": "east_bay", "address": "22373 N Third St, Hayward, CA 94541",
        "lat": 37.6690, "lng": -122.0822,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("9am–5pm", "9am–5pm"), "admission": free(),
        "phone": "(510) 881-6715", "website": "https://hayward-ca.gov",
        "rating": 4.6, "review_count": 1100,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Albany Bulb — Shoreline Park",
        "city": "Albany", "neighborhood": "Albany Waterfront",
        "region": "east_bay", "address": "1 Buchanan St, Albany, CA 94706",
        "lat": 37.8908, "lng": -122.3207,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.5, "review_count": 1300,
        "stroller_friendly": False, "has_restrooms": False,
    },
    {
        "name": "Bounce U — Pleasanton",
        "city": "Pleasanton", "neighborhood": "Hacienda",
        "region": "east_bay", "address": "4555 Hopyard Rd Ste 10, Pleasanton, CA 94588",
        "lat": 37.6918, "lng": -121.9011,
        "category": "trampoline_park", "venue_type": "indoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("9am–8pm", "9am–9pm"), "admission": paid(15, 0),
        "phone": "(925) 555-0143", "website": None,
        "rating": 4.4, "review_count": 720,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Pleasanton Public Library",
        "city": "Pleasanton", "neighborhood": "Downtown",
        "region": "east_bay", "address": "400 Old Bernal Ave, Pleasanton, CA 94566",
        "lat": 37.6629, "lng": -121.8783,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–9pm", "10am–5pm"), "admission": free(),
        "phone": "(925) 931-3400", "website": "https://alameda.lib.ca.us",
        "rating": 4.6, "review_count": 380,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "San Leandro Marina Park",
        "city": "San Leandro", "neighborhood": "Marina",
        "region": "east_bay", "address": "68 Monarch Bay Dr, San Leandro, CA 94577",
        "lat": 37.6979, "lng": -122.1973,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("5am–10pm", "5am–10pm"), "admission": free(),
        "phone": "(510) 577-3462", "website": "https://sanleandro.org",
        "rating": 4.5, "review_count": 1600,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Danville Oak Hill Park",
        "city": "Danville", "neighborhood": "Danville",
        "region": "east_bay", "address": "825 Camino Ramon, Danville, CA 94526",
        "lat": 37.8211, "lng": -121.9910,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 120,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.6, "review_count": 490,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Concord Aquatic Center",
        "city": "Concord", "neighborhood": "Downtown Concord",
        "region": "east_bay", "address": "3575 Clayton Rd, Concord, CA 94519",
        "lat": 37.9813, "lng": -122.0292,
        "category": "swimming", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("5:30am–9pm", "8am–6pm"), "admission": paid(5, 7),
        "phone": "(925) 671-3440", "website": "https://cityofconcord.org",
        "rating": 4.3, "review_count": 360,
        "stroller_friendly": False, "has_restrooms": True,
    },

    # ── NORTH BAY (20) ────────────────────────────────────────────────────────
    {
        "name": "Bay Model Visitor Center",
        "city": "Sausalito", "neighborhood": "Marinship",
        "region": "north_bay", "address": "2100 Bridgeway, Sausalito, CA 94965",
        "lat": 37.8581, "lng": -122.4987,
        "category": "museum", "venue_type": "indoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("9am–4pm", "10am–5pm"), "admission": free(),
        "phone": "(415) 332-3871", "website": "https://spn.usace.army.mil/baymodel",
        "rating": 4.6, "review_count": 1450,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Muir Woods National Monument",
        "city": "Mill Valley", "neighborhood": "Muir Woods",
        "region": "north_bay", "address": "1 Muir Woods Rd, Mill Valley, CA 94941",
        "lat": 37.8910, "lng": -122.5710,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": paid(15, 15),
        "phone": "(415) 388-2596", "website": "https://nps.gov/muwo",
        "rating": 4.8, "review_count": 12000,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Stafford Lake Park",
        "city": "Novato", "neighborhood": "Novato",
        "region": "north_bay", "address": "1000 Novato Blvd, Novato, CA 94947",
        "lat": 38.0887, "lng": -122.6043,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": "(415) 473-4220", "website": "https://marincounty.gov",
        "rating": 4.6, "review_count": 1200,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Marin Art & Garden Center",
        "city": "Ross", "neighborhood": "Ross",
        "region": "north_bay", "address": "30 Sir Francis Drake Blvd, Ross, CA 94957",
        "lat": 37.9626, "lng": -122.5540,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("9am–5pm", "9am–5pm"), "admission": free(),
        "phone": "(415) 454-5597", "website": "https://magc.org",
        "rating": 4.7, "review_count": 870,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Terra Linda Community Center Pool",
        "city": "San Rafael", "neighborhood": "Terra Linda",
        "region": "north_bay", "address": "670 Del Ganado Rd, San Rafael, CA 94903",
        "lat": 37.9894, "lng": -122.5472,
        "category": "swimming", "venue_type": "both",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("6am–9pm", "8am–5pm"), "admission": paid(5, 7),
        "phone": "(415) 485-3344", "website": "https://cityofsanrafael.org",
        "rating": 4.3, "review_count": 210,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Phoenix Lake Trail",
        "city": "Ross", "neighborhood": "Lagunitas",
        "region": "north_bay", "address": "Natalie Coffin Greene Park, Ross, CA 94957",
        "lat": 37.9479, "lng": -122.5619,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": "https://marinwater.org",
        "rating": 4.8, "review_count": 2300,
        "stroller_friendly": False, "has_restrooms": False,
    },
    {
        "name": "China Camp State Park",
        "city": "San Rafael", "neighborhood": "McNears Beach",
        "region": "north_bay", "address": "101 Peacock Gap Trail, San Rafael, CA 94901",
        "lat": 38.0040, "lng": -122.4761,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("8am–Sunset", "8am–Sunset"), "admission": paid(8, 8),
        "phone": "(415) 456-0766", "website": "https://parks.ca.gov",
        "rating": 4.7, "review_count": 2100,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "Muir Beach",
        "city": "Muir Beach", "neighborhood": "Muir Beach",
        "region": "north_bay", "address": "1 Pacific Way, Muir Beach, CA 94965",
        "lat": 37.8609, "lng": -122.5793,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": "https://nps.gov/goga",
        "rating": 4.8, "review_count": 3800,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "San Anselmo Memorial Park",
        "city": "San Anselmo", "neighborhood": "Downtown",
        "region": "north_bay", "address": "1 Tunstead Ave, San Anselmo, CA 94960",
        "lat": 37.9748, "lng": -122.5614,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.5, "review_count": 530,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Mill Valley Library — Children's Room",
        "city": "Mill Valley", "neighborhood": "Downtown",
        "region": "north_bay", "address": "375 Throckmorton Ave, Mill Valley, CA 94941",
        "lat": 37.9071, "lng": -122.5449,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–6pm", "10am–5pm"), "admission": free(),
        "phone": "(415) 389-4292", "website": "https://millvalleylibrary.net",
        "rating": 4.7, "review_count": 360,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Blackie's Pasture",
        "city": "Tiburon", "neighborhood": "Tiburon",
        "region": "north_bay", "address": "101 Tiburon Blvd, Tiburon, CA 94920",
        "lat": 37.8808, "lng": -122.4608,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.8, "review_count": 1900,
        "stroller_friendly": True, "has_restrooms": False,
    },
    {
        "name": "Corte Madera Community Center",
        "city": "Corte Madera", "neighborhood": "Downtown",
        "region": "north_bay", "address": "498 Tamalpais Dr, Corte Madera, CA 94925",
        "lat": 37.9254, "lng": -122.5218,
        "category": "sports", "venue_type": "indoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("8am–9pm", "8am–5pm"), "admission": paid(5, 5),
        "phone": "(415) 927-5072", "website": "https://townofcortemadera.org",
        "rating": 4.3, "review_count": 180,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Novato Community Pool",
        "city": "Novato", "neighborhood": "Downtown",
        "region": "north_bay", "address": "640 Atherton Ave, Novato, CA 94945",
        "lat": 38.1068, "lng": -122.5690,
        "category": "swimming", "venue_type": "both",
        "min_age_months": 6, "max_age_months": 144,
        "hours": h("6am–9pm", "8am–6pm"), "admission": paid(4, 6),
        "phone": "(415) 897-4335", "website": "https://novato.org",
        "rating": 4.2, "review_count": 150,
        "stroller_friendly": False, "has_restrooms": True,
    },
    {
        "name": "McNear's Beach Park",
        "city": "San Rafael", "neighborhood": "East San Rafael",
        "region": "north_bay", "address": "1010 Point San Pedro Rd, San Rafael, CA 94901",
        "lat": 37.9811, "lng": -122.4675,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 144,
        "hours": h("9am–7pm", "9am–7pm"), "admission": paid(5, 5),
        "phone": "(415) 499-6387", "website": "https://marincounty.gov",
        "rating": 4.5, "review_count": 1400,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Peacock Gap Neighborhood Park",
        "city": "San Rafael", "neighborhood": "Peacock Gap",
        "region": "north_bay", "address": "400 Biscayne Dr, San Rafael, CA 94901",
        "lat": 37.9737, "lng": -122.4742,
        "category": "playground", "venue_type": "outdoor",
        "min_age_months": 12, "max_age_months": 108,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.4, "review_count": 220,
        "stroller_friendly": True, "has_restrooms": False,
    },
    {
        "name": "Larkspur Landing Park",
        "city": "Larkspur", "neighborhood": "Larkspur Landing",
        "region": "north_bay", "address": "Larkspur Landing Cir, Larkspur, CA 94939",
        "lat": 37.9454, "lng": -122.5011,
        "category": "park", "venue_type": "outdoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("Dawn–Dusk", "Dawn–Dusk"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.5, "review_count": 390,
        "stroller_friendly": True, "has_restrooms": False,
    },
    {
        "name": "San Rafael Community Library",
        "city": "San Rafael", "neighborhood": "Downtown",
        "region": "north_bay", "address": "1100 E St, San Rafael, CA 94901",
        "lat": 37.9735, "lng": -122.5279,
        "category": "library", "venue_type": "indoor",
        "min_age_months": 0, "max_age_months": 144,
        "hours": h("10am–8pm", "10am–5pm"), "admission": free(),
        "phone": "(415) 485-3321", "website": "https://cityofsanrafael.org",
        "rating": 4.5, "review_count": 420,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Tiburon Uplands Nature Preserve",
        "city": "Tiburon", "neighborhood": "Tiburon",
        "region": "north_bay", "address": "100 Greenwood Cove Dr, Tiburon, CA 94920",
        "lat": 37.8875, "lng": -122.4585,
        "category": "nature_trail", "venue_type": "outdoor",
        "min_age_months": 36, "max_age_months": 144,
        "hours": h("Sunrise–Sunset", "Sunrise–Sunset"), "admission": free(),
        "phone": None, "website": None,
        "rating": 4.7, "review_count": 610,
        "stroller_friendly": False, "has_restrooms": False,
    },
    {
        "name": "Jungle Fun Zone — Novato",
        "city": "Novato", "neighborhood": "Hamilton",
        "region": "north_bay", "address": "5800 Nave Dr, Novato, CA 94949",
        "lat": 38.0832, "lng": -122.5482,
        "category": "indoor_play", "venue_type": "indoor",
        "min_age_months": 6, "max_age_months": 84,
        "hours": h("9am–6pm", "9am–6pm"), "admission": paid(12, 0),
        "phone": "(415) 555-0167", "website": None,
        "rating": 4.3, "review_count": 290,
        "stroller_friendly": True, "has_restrooms": True,
    },
    {
        "name": "Marin County Fair Fairgrounds",
        "city": "San Rafael", "neighborhood": "Downtown",
        "region": "north_bay", "address": "10 Avenue of the Flags, San Rafael, CA 94903",
        "lat": 37.9923, "lng": -122.5302,
        "category": "farm", "venue_type": "outdoor",
        "min_age_months": 24, "max_age_months": 144,
        "hours": h("9am–5pm", "9am–5pm"), "admission": paid(10, 15),
        "phone": "(415) 499-6400", "website": "https://marinfair.org",
        "rating": 4.5, "review_count": 1800,
        "stroller_friendly": True, "has_restrooms": True,
    },
]


def run(dry_run: bool = False) -> None:
    print(f"\n{'='*55}")
    print("KidVenture Fake Data Seeder")
    print(f"  Total venues : {len(VENUES)}")
    print(f"  Dry run      : {dry_run}")
    print(f"{'='*55}\n")

    if dry_run:
        for i, v in enumerate(VENUES, 1):
            print(
                f"  {i:3}. [{v['region']:10}] {v['name'][:45]:45} "
                f"cat={v['category']:14} "
                f"age={v['min_age_months']:3}-{v['max_age_months']:3}mo  "
                f"⭐{v['rating']}"
            )
        print(f"\n[DRY RUN] {len(VENUES)} venues listed — nothing written.\n")
        return

    from supabase import create_client
    client = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)

    records = [
        {**venue, "data_source": "mock"}
        for venue in VENUES
    ]

    try:
        # Upsert in batches of 25 to stay within Supabase free-tier limits
        batch_size = 25
        total_written = 0
        for i in range(0, len(records), batch_size):
            batch = records[i: i + batch_size]
            response = client.table("venues").upsert(batch).execute()
            count = len(response.data) if response.data else 0
            total_written += count
            print(f"  Batch {i // batch_size + 1}: wrote {count} venues")

        print(f"\n✓ Done — {total_written} venues written to Supabase.\n")
    except Exception as e:
        print(f"\n✗ Error writing to Supabase: {e}\n")
        raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed KidVenture with fake venue data")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print venues without writing to Supabase")
    args = parser.parse_args()
    run(dry_run=args.dry_run)
